"""
bot/telegram_bot.py

Two responsibilities:
1. send_daily_digest() - formats today's picks and sends them as one
   message via the Telegram Bot API. Called from run_daily.py right
   after jobs/select_picks.py runs.

2. A small polling loop handling /stake replies, so you can record what
   you actually staked on a pick without needing any UI - e.g. sending
   "/stake 23 10" records a stake of 10 naira on pick_id 23.

HOW IT WORKS:
- Model uses Pinnacle as the reference bookmaker (sharpest odds, best signal)
- You place the actual bet on Sportybet
- The message shows the Pinnacle reference price + a minimum acceptable
  price on Sportybet so you know when to place vs skip

Setup: message @BotFather on Telegram, run /newbot, copy the token into
TELEGRAM_BOT_TOKEN. To get your chat_id, message your new bot once, then
visit https://api.telegram.org/bot<TOKEN>/getUpdates and read chat.id.

Run the digest: python -m bot.telegram_bot send
Run stake listener: python -m bot.telegram_bot listen
"""

import sys
import requests
from datetime import datetime, date

from config import TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID
from db.connection import get_cursor

API_BASE = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}"


def send_message(text: str):
    response = requests.post(
        f"{API_BASE}/sendMessage",
        data={"chat_id": TELEGRAM_CHAT_ID, "text": text, "parse_mode": "HTML"},
        timeout=15,
    )
    response.raise_for_status()
    return response.json()


def get_todays_picks(cur) -> list[dict]:
    cur.execute(
        """
        SELECT p.pick_id, p.outcome, p.your_odds, p.ev_pct, p.model_probability,
               ht.name as home_team, at.name as away_team, f.kickoff_time
        FROM picks p
        JOIN fixtures f ON f.fixture_id = p.fixture_id
        JOIN teams ht ON ht.team_id = f.home_team_id
        JOIN teams at ON at.team_id = f.away_team_id
        WHERE p.flagged_at::date = CURRENT_DATE
        ORDER BY p.ev_pct DESC
        """
    )
    return cur.fetchall()


def format_digest(picks: list[dict]) -> str:
    if not picks:
        return (
            f"<b>Value Picks — {date.today().strftime('%d %b %Y')}</b>\n\n"
            "No bets cleared the EV threshold today.\n"
            "This is normal on low-edge days, not an error."
        )

    outcome_label = {"home": "Home win", "draw": "Draw", "away": "Away win"}

    lines = [
        f"<b>Value Picks — {date.today().strftime('%d %b %Y')}</b>",
        "<i>Reference odds: Pinnacle. Place bets on Sportybet.</i>\n",
    ]

    for i, p in enumerate(picks, 1):
        kickoff_str = p["kickoff_time"].strftime("%H:%M UTC")
        outcome = outcome_label[p["outcome"]]
        pinnacle_odds = float(p["your_odds"])
        ev = float(p["ev_pct"])
        model_prob = float(p["model_probability"])

        # Sportybet price guidance:
        # >= Pinnacle price  -> full green light, full edge intact
        # >= 95% of Pinnacle -> still acceptable, edge shrinks slightly
        # <  95% of Pinnacle -> skip, edge likely gone after bookmaker margin
        min_acceptable = round(pinnacle_odds * 0.95, 2)

        lines.append(
            f"<b>{i}. {p['home_team']} vs {p['away_team']}</b>\n"
            f"   Kickoff: {kickoff_str}\n"
            f"   Pick: <b>{outcome}</b>\n"
            f"   Pinnacle ref: <code>{pinnacle_odds:.2f}</code> | Model: <code>{model_prob:.0%}</code> | EV: <code>{ev:+.1f}%</code>\n"
            f"   Place on Sportybet if odds >= <code>{pinnacle_odds:.2f}</code> (full edge)\n"
            f"   Still ok if odds >= <code>{min_acceptable}</code> (reduced edge)\n"
            f"   Skip if Sportybet shows below <code>{min_acceptable}</code>\n"
            f"   /stake {p['pick_id']} &lt;amount&gt; after placing"
        )

    lines.append(
        "\n<i>Picks generated by Poisson model + EV scoring.</i>\n"
        "<i>Always check Sportybet price before placing.</i>"
    )
    return "\n\n".join(lines)


def send_daily_digest():
    with get_cursor(commit=False) as cur:
        picks = get_todays_picks(cur)

    message = format_digest(picks)
    send_message(message)
    print(f"[{datetime.now()}] Sent digest with {len(picks)} pick(s).")


def record_stake(pick_id: int, stake: float) -> bool:
    with get_cursor(commit=True) as cur:
        cur.execute(
            "UPDATE picks SET stake = %s WHERE pick_id = %s RETURNING pick_id",
            (stake, pick_id),
        )
        return cur.fetchone() is not None


def handle_update(update: dict):
    message = update.get("message", {})
    text = message.get("text", "")

    if text.startswith("/stake"):
        parts = text.split()
        if len(parts) != 3:
            send_message("Usage: /stake <pick_id> <amount>\nExample: /stake 23 10")
            return
        try:
            pick_id = int(parts[1])
            stake = float(parts[2])
        except ValueError:
            send_message("pick_id and amount must be numbers.\nExample: /stake 23 10")
            return

        found = record_stake(pick_id, stake)
        if found:
            send_message(f"Recorded stake of {stake} naira on pick #{pick_id}. Good luck!")
        else:
            send_message(f"No pick found with id {pick_id}. Check the pick number in today's message.")


def poll_for_updates():
    """
    Long-polling loop for /stake commands. Run this as a background
    process or alongside the daily job - it stays alive waiting for
    your replies.
    """
    print("Listening for /stake commands... (Ctrl+C to stop)")
    offset = None
    while True:
        params = {"timeout": 30}
        if offset is not None:
            params["offset"] = offset

        response = requests.get(f"{API_BASE}/getUpdates", params=params, timeout=35)
        updates = response.json().get("result", [])

        for update in updates:
            handle_update(update)
            offset = update["update_id"] + 1


if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1] not in ("send", "listen"):
        print("Usage: python -m bot.telegram_bot [send|listen]")
        sys.exit(1)

    if sys.argv[1] == "send":
        send_daily_digest()
    elif sys.argv[1] == "listen":
        poll_for_updates()
